import { Metadata } from 'next';
import Table from '@/app/ui/audiobooks/table';

export const metadata: Metadata = {
  title: 'Audio Books',
};

export default async function Page() {
  const books = [
    {
      id: '1',
      url: 'https://www.youtube.com/watch?v=2P1-SunHlZg',
      title: '48 Laws of Power',
      author: 'Robert Greene',
    },
    {
      id: '2',
      url: 'https://www.youtube.com/watch?v=lUycsN3HrPc',
      title: '20,000 Leagues Under the Sea',
      author: 'Jules Verne',
    },
    {
      id: '3',
      url: 'https://www.youtube.com/watch?v=N_KpQivx9kk',
      title: 'A Christmas Carol',
      author: 'Charles Dickens',
    },
    {
      id: '4',
      url: 'https://www.youtube.com/watch?v=WX_qyVwwr8Q',
      title: "A Midsummer Night's Dream",
      author: 'William Shakespeare',
    },
    {
      id: '5',
      url: 'https://www.youtube.com/watch?v=E6XWbksiT-o',
      title: 'A Modest Proposal',
      author: 'Jonathan Swift',
    },
    {
      id: '6',
      url: 'https://www.youtube.com/watch?v=wd8vr87k6Fc',
      title: 'A Tale of Two Cities',
      author: 'Charles Dickens',
    },
    {
      id: '7',
      url: 'https://www.youtube.com/watch?v=1g7BWguMkUM',
      title: 'Adventure of Abbey Grange',
      author: 'Sir Arthur Conan Doyle',
    },
    {
      id: '8',
      url: 'https://www.youtube.com/watch?v=VKNGnXA1ix8',
      title: 'Adventures of Huckleberry Finn',
      author: 'Mark Twain',
    },
    {
      id: '9',
      url: 'https://www.youtube.com/watch?v=15R_-_Wl6fs',
      title: 'Adventures of Sherlock Holmes',
      author: 'Sir Arthur Conan Doyle',
    },
    {
      id: '10',
      url: 'https://www.youtube.com/watch?v=TxiTNSDCsf0',
      title: 'Adventures of Tom Sawyer',
      author: 'Mark Twain',
    },
    {
      id: '11',
      url: 'https://www.youtube.com/watch?v=ycgkogD7Jw4',
      title: 'Age of Reason',
      author: 'Thomas Paine',
    },
    {
      id: '12',
      url: 'https://www.youtube.com/watch?v=D4G5Vut8fzg',
      title: 'Alchemist',
      author: 'Paulo Coelho',
    },
    {
      id: '13',
      url: 'https://www.youtube.com/watch?v=yEk-SZh_9Jw',
      title: 'Alice in Wonderland',
      author: 'Lewis Carroll',
    },
    {
      id: '14',
      url: 'https://www.youtube.com/watch?v=-kjWJjtMwuQ',
      title: 'Anna Karenina',
      author: 'Leo Tolstoy',
    },
    {
      id: '15',
      url: 'https://www.youtube.com/watch?v=9tlkTOPYU6I',
      title: 'Anne of Green Gables',
      author: 'Lucy Maud Montgomery',
    },
    {
      id: '16',
      url: 'https://www.youtube.com/watch?v=xVGkArXTZxk',
      title: 'Around the World in 80 Days',
      author: 'Jules Verne',
    },
    {
      id: '17',
      url: 'https://www.youtube.com/watch?v=tfIGKc6jEhA',
      title: 'Art of War',
      author: 'Sun Tzu',
    },
    {
      id: '18',
      url: 'https://www.youtube.com/watch?v=Ovz9VspYOxY',
      title: 'Atlas of the Heart',
      author: 'Brene Brown',
    },
    {
      id: '19',
      url: 'https://www.youtube.com/watch?v=3kTS1Ex-dig',
      title: 'Beowulf',
      author: 'unknown',
    },
    {
      id: '20',
      url: 'https://www.youtube.com/watch?v=vboAs2q2mYI',
      title: 'Beyond Good and Evil',
      author: 'Friedrich Nietzsche',
    },
    {
      id: '21',
      url: 'https://www.youtube.com/watch?v=0zqoGDVed8A',
      title: 'Bushido: The Way of the Warrior - Soul of Japan',
      author: 'Inazo Nitobe',
    },
    {
      id: '22',
      url: 'https://www.youtube.com/watch?v=F9B7L9O803s',
      title: 'Call of the Wild',
      author: 'Jack London',
    },
    {
      id: '23',
      url: 'https://www.youtube.com/watch?v=ot74dEJKADg',
      title: 'Catcher in the Rye',
      author: 'J.D. Salinger',
    },
    {
      id: '24',
      url: 'https://www.youtube.com/watch?v=vVL9TtxDu60',
      title: 'Color Purple',
      author: 'Alice Walker',
    },
    {
      id: '25',
      url: 'https://www.youtube.com/watch?v=PdYLRTGmQ3c',
      title: 'Communist Manifesto',
      author: 'Karl Marx',
    },
    {
      id: '26',
      url: 'https://www.youtube.com/watch?v=XOxIQnjmmZw',
      title: 'Count of Monte Cristo',
      author: 'Alexandre Dumas',
    },
    {
      id: '27',
      url: 'https://www.youtube.com/watch?v=cD6TCxizFjs',
      title: 'Dhammapada',
      author: 'Buddha',
    },
    {
      id: '28',
      url: 'https://www.youtube.com/watch?v=0Ny0mu0qFCA',
      title: 'Divine Comedy',
      author: 'Dante',
    },
    {
      id: '29',
      url: 'https://www.youtube.com/watch?v=TUJ5Y1QjLwk',
      title: 'Dracula',
      author: 'Bram Stoker',
    },
    {
      id: '30',
      url: 'https://www.youtube.com/watch?v=bG5QixsoPok',
      title: 'Fahrenheit 451',
      author: 'Ray Bradbury',
    },
    {
      id: '31',
      url: 'https://www.youtube.com/watch?v=YzyDRSMee_U',
      title: 'Fisherman and His Soul',
      author: 'Oscar Wilde',
    },
    {
      id: '32',
      url: 'https://www.youtube.com/watch?v=tETWQO2UXmQ',
      title: 'Frankenstein',
      author: 'Mary Shelley',
    },
    {
      id: '33',
      url: 'https://www.youtube.com/watch?v=14ZRQPSOgaY',
      title: 'Gambler',
      author: 'Fyodor Dostoyevsky',
    },
    {
      id: '34',
      url: 'https://www.youtube.com/watch?v=kI4rrTPFVd4',
      title: 'Genesis',
      author: 'Moses',
    },
    {
      id: '35',
      url: 'https://www.youtube.com/watch?v=YA18xKvOK94',
      title: 'Great Expectations',
      author: 'Charles Dickens',
    },
    {
      id: '36',
      url: 'https://www.youtube.com/watch?v=ZjHl5TyWMsQ',
      title: 'Great Gatsby',
      author: 'F.Scott Fitzgerald',
    },
    {
      id: '37',
      url: 'https://www.youtube.com/watch?v=7J-1pMESTI0',
      title: "Grimm's Fairy Tales",
      author: 'Brothers Grimm',
    },
    {
      id: '38',
      url: 'https://www.youtube.com/watch?v=6_Y-tYrGBDc',
      title: 'Hamlet',
      author: 'William Shakespeare',
    },
    {
      id: '39',
      url: 'https://www.youtube.com/watch?v=0pmWf1k-vFM',
      title: "Handmaid's Tale",
      author: 'Margaret Atwood',
    },
    {
      id: '40',
      url: 'https://www.youtube.com/watch?v=Qji-GeY_NqM',
      title: 'Hansel and Gretel',
      author: 'Brothers Grimm',
    },
    {
      id: '41',
      url: 'https://www.youtube.com/watch?v=IsZsIjMz5Cg',
      title: "Harry Potter and the Sorcerer's Stone",
      author: 'J.K. Rowling',
    },
    {
      id: '42',
      url: 'https://www.youtube.com/watch?v=at-l2oL9ED8',
      title: 'Hills Like White Elephants',
      author: 'Earnest Hemingway',
    },
    {
      id: '43',
      url: 'https://www.youtube.com/watch?v=Z2XjCtPNvWA',
      title: 'How Successful People Think',
      author: 'John Maxwell',
    },
    {
      id: '44',
      url: 'https://www.youtube.com/watch?v=YKAfKprBXQc',
      title: 'How To Win Friends And Influence People',
      author: 'Dale Carnegie',
    },
    {
      id: '45',
      url: 'https://www.youtube.com/watch?v=Wgs1hLhSc2g',
      title: 'Iliad',
      author: 'Homer',
    },
    {
      id: '46',
      url: 'https://www.youtube.com/watch?v=sBF1ZpbGEEE',
      title: 'Invisible Man',
      author: 'H.G. Wells',
    },
    {
      id: '47',
      url: 'https://www.youtube.com/watch?v=lnLahYbq_7Q',
      title: 'Julius Caesar',
      author: 'William Shakespeare',
    },
    {
      id: '48',
      url: 'https://www.youtube.com/watch?v=WRJ2-GKL1SQ',
      title: 'Jungle',
      author: 'Upton Sinclair',
    },
    {
      id: '49',
      url: 'https://www.youtube.com/watch?v=L-mB7F4B1Hw',
      title: 'Jungle Book',
      author: 'Rudyard Kipling',
    },
    {
      id: '50',
      url: 'https://www.youtube.com/watch?v=jA4_2IM8X-U',
      title: 'Legend of Sleepy Hollow',
      author: 'Washington Irving',
    },
    {
      id: '51',
      url: 'https://www.youtube.com/watch?v=57aViPgDDjU',
      title: 'Les Misérables',
      author: 'Victor Hugo',
    },
    {
      id: '52',
      url: 'https://www.youtube.com/watch?v=39D8QS4CtrI',
      title: 'Letters to a Young Poet',
      author: 'Rainer Maria Rilke',
    },
    {
      id: '53',
      url: 'https://www.youtube.com/watch?v=GiOeoxSG0D0',
      title: 'Life and Adventures of Robinson Crusoe',
      author: 'Daniel Defoe',
    },
    {
      id: '54',
      url: 'https://www.youtube.com/watch?v=XKGrUjwv-yA',
      title: 'Little Prince',
      author: 'Antoine De Saint-Exupery',
    },
    {
      id: '55',
      url: 'https://www.youtube.com/watch?v=1Y1imN6k32w',
      title: 'Little Women',
      author: 'Louisa May Alcott',
    },
    {
      id: '56',
      url: 'https://www.youtube.com/watch?v=utRA2Ck3swU',
      title: 'Lord of the Flies',
      author: 'William Golding',
    },
    {
      id: '57',
      url: 'https://www.youtube.com/watch?v=aeCiiXULIVM',
      title: 'Lost World',
      author: 'Sir Arthur Conan Doyle',
    },
    {
      id: '58',
      url: 'https://www.youtube.com/watch?v=pGBQsQoWvA0',
      title: 'Macbeth',
      author: 'William Shakespeare',
    },
    {
      id: '59',
      url: 'https://www.youtube.com/watch?v=MBCPeqla5bE',
      title: 'Merchant of Venice',
      author: 'William Shakespeare',
    },
    {
      id: '60',
      url: 'https://www.youtube.com/watch?v=uDDoIGX3bHU',
      title: 'Moby Dick',
      author: 'Herman Melville',
    },
    {
      id: '61',
      url: 'https://www.youtube.com/watch?v=lI6cgH3sVE4',
      title: 'My Inventions',
      author: 'Nikola Tesla',
    },
    {
      id: '62',
      url: 'https://www.youtube.com/watch?v=8a8xw4YO6AA',
      title: 'Underground',
      author: 'Fyodor Dostoyevsky',
    },
    {
      id: '63',
      url: 'https://www.youtube.com/watch?v=vrDAp5lnddQ',
      title: 'Odyssey',
      author: 'Homer',
    },
    {
      id: '64',
      url: 'https://www.youtube.com/watch?v=TM33XRK--u0',
      title: 'Oedipus Rex',
      author: 'Sophocles',
    },
    {
      id: '65',
      url: 'https://www.youtube.com/watch?v=GwsOgHASmyU',
      title: 'Of Mice and Men',
      author: 'John Steinbeck',
    },
    {
      id: '66',
      url: 'https://www.youtube.com/watch?v=JXxy63IW7-Y',
      title: 'Old Man And The Sea The',
      author: 'Ernest Hemingway',
    },
    {
      id: '67',
      url: 'https://www.youtube.com/watch?v=cUVyaRJhKwc',
      title: 'Oliver Twist',
      author: 'Charles Dickens',
    },
    {
      id: '68',
      url: 'https://www.youtube.com/watch?v=NJ0iKf7bogw',
      title: 'Origin of Species',
      author: 'Charles Darwin',
    },
    {
      id: '69',
      url: 'https://www.youtube.com/watch?v=p4vsFO1mh4o',
      title: 'Othello',
      author: 'William Shakespeare',
    },
    {
      id: '70',
      url: 'https://www.youtube.com/watch?v=0hu8p-NYSkE',
      title: 'Paradise Lost',
      author: 'John Milton',
    },
    {
      id: '71',
      url: 'https://www.youtube.com/watch?v=09LUC7rNOEE',
      title: 'Persuasion',
      author: 'Jane Austen',
    },
    {
      id: '72',
      url: 'https://www.youtube.com/watch?v=l4GhL9PzPDU',
      title: 'Peter Pan',
      author: 'J.M. Barrie',
    },
    {
      id: '73',
      url: 'https://www.youtube.com/watch?v=Ksn2pwKN0WI',
      title: 'Picture of Dorian Gray',
      author: 'Oscar Wilde',
    },
    {
      id: '74',
      url: 'https://www.youtube.com/watch?v=FIiS0R7ifQQ',
      title: 'Phantom of the Opera',
      author: 'Gaston Leroux',
    },
    {
      id: '75',
      url: 'https://www.youtube.com/watch?v=m8JGdNKiw-c',
      title: 'Pride and Prejudice',
      author: 'Jane Austen',
    },
    {
      id: '76',
      url: 'https://www.youtube.com/watch?v=BH7AQAxq1ac',
      title: 'Prince and the Pauper',
      author: 'Mark Twain',
    },
    {
      id: '77',
      url: 'https://www.youtube.com/watch?v=AtGlWlg4-44',
      title: 'Raven',
      author: 'Edgar Allan Poe',
    },
    {
      id: '78',
      url: 'https://www.youtube.com/watch?v=GFiBbPk5Ns0',
      title: 'Richard III',
      author: 'William Shakespeare',
    },
    {
      id: '79',
      url: 'https://www.youtube.com/watch?v=RdvdaCnVuy8',
      title: 'Roughing It',
      author: 'Mark Twain',
    },
    {
      id: '80',
      url: 'https://www.youtube.com/watch?v=e4tSfkGyC74',
      title: 'Romeo And Juliet',
      author: 'William Shakespeare',
    },
    {
      id: '81',
      url: 'https://www.youtube.com/watch?v=7qaKd0kMHAs',
      title: 'Sayings of Confucius',
      author: 'Confucius',
    },
    {
      id: '82',
      url: 'https://www.youtube.com/watch?v=udvHrcJGIAA',
      title: 'Scarlet Letter',
      author: 'Nathaniel Hawthorne',
    },
    {
      id: '83',
      url: 'https://www.youtube.com/watch?v=Yx_GpxQvi5E',
      title: 'Secret Garden',
      author: 'Frances Hodgson Burnett',
    },
    {
      id: '84',
      url: 'https://www.youtube.com/watch?v=PVwh6EcMvXs',
      title: 'Sherlock Holmes: A Study in Scarlet',
      author: 'Sir Arthur Conan Doyle',
    },
    {
      id: '85',
      url: 'https://www.youtube.com/watch?v=_MXfeMIJtxc',
      title: 'Sherlock Holmes: The Hound of the Baskervilles',
      author: 'Sir Arthur Conan Doyle',
    },
    {
      id: '86',
      url: 'https://www.youtube.com/watch?v=Yz6uGkdenEk',
      title: 'Slaughterhouse Five',
      author: 'Kurt Vonnegut',
    },
    {
      id: '87',
      url: 'https://www.youtube.com/watch?v=kq5qtTZBH_8',
      title: 'Strange Case of Dr. Jekyll and Mr. Hyde',
      author: 'R.L. Stevenson',
    },
    {
      id: '88',
      url: 'https://www.youtube.com/watch?v=RH3TgyKhNz8',
      title: 'Studies In Pessimism',
      author: 'Arthur Schopenhauer',
    },
    {
      id: '89',
      url: 'https://www.youtube.com/watch?v=wnvQsK0KLfc',
      title: 'Tarzan of the Apes',
      author: 'Edgar Rice Burroughs',
    },
    {
      id: '90',
      url: 'https://www.youtube.com/watch?v=CMb4phUnSNI',
      title: 'Tempest',
      author: 'William Shakespeare',
    },
    {
      id: '91',
      url: 'https://www.youtube.com/watch?v=io8JSc5q3VA',
      title: 'Theory of Relativity',
      author: 'Albert Einstein',
    },
    {
      id: '92',
      url: 'https://www.youtube.com/watch?v=XODFEs8Gspk',
      title: 'To Kill A Mockingbird',
      author: 'Harper Lee',
    },
    {
      id: '93',
      url: 'https://www.youtube.com/watch?v=BZFIJ9p0c2A',
      title: 'Treasure Island',
      author: 'Robert Louis Stevenson',
    },
    {
      id: '94',
      url: 'https://www.youtube.com/watch?v=SAXvhAQwJK0',
      title: 'Twelve Years a Slave',
      author: 'Solomon Northup',
    },
    {
      id: '95',
      url: 'https://www.youtube.com/watch?v=2PLC139t8EY',
      title: 'War of the Worlds',
      author: 'H.G. Wells',
    },
    {
      id: '96',
      url: 'https://www.youtube.com/watch?v=X_6aaH2gtIg',
      title: 'Walden',
      author: 'Henry David Thoreau',
    },
    {
      id: '97',
      url: 'https://www.youtube.com/watch?v=AU3L62OomvQ',
      title: 'Wind of the Willows',
      author: 'Kenneth Grahame',
    },
    {
      id: '98',
      url: 'https://www.youtube.com/watch?v=jYIaUmnGLj4',
      title: 'Wonderful Wizard of Oz',
      author: 'L. Frank Baum',
    },
    {
      id: '99',
      url: 'https://www.youtube.com/watch?v=FzbOAR7N5WU',
      title: 'Wuthering Heights',
      author: 'Emily Brontë',
    },
  ];

  return (
    <div className="w-full">
      <div className="flex w-full items-center justify-between">
        <main>
          <Table books={books} />
        </main>
      </div>
    </div>
  );
}
